name: archlinux

on:
  schedule:
    - cron: '25 18 * * *'

env:
  LOGIN_NAME: coshapp

jobs:

  # Push image to DockerHub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username okadash --password-stdin

      - name: Build and push Archlinux images
        run: |
          . workflow_functions.sh
          coshapp_ver=latest build_image Archlinux/*

