name: build-and-push-weekly

on:
  schedule:
    - cron: '3 20 * * 6'

env:
  LOGIN_NAME: coshapp

jobs:

  # Push image to DockerHub.
  rolling-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username okadash --password-stdin

      - name: Build and push Archlinux Base images
        run: |
          . .github_script.sh
          build_image Archlinux/*
          push_image Archlinux/*
